### ISSUE TITLE
Not able to reach you by email

### ISSUE THREAD

**Issue by RockyTDR** [mlocati/audacity-pot#1]
Hi Michele

I'm sorry to make an "issue" like this, but I hope this reaches you! Apparently, I'm unable to send you emails. All messages are rejected (unable to deliver).

Regards

Thomas

**Comment by mlocati** [comment]
That's really strange. Do you have an error message?

**Comment by RockyTDR** [comment]
Yes... partially Dutch, sorry:

Uw bericht kan niet worden bezorgd bij de volgende geadresseerden of groepen:

Michele Locati (michele@locati.it)
Het bericht is niet afgeleverd. Ondanks herhaalde pogingen om het bericht af te leveren, kan er geen verbinding worden gemaakt met de externe server.

Neem op een andere manier (bijvoorbeeld telefonisch) contact op met de geadresseerde en vraag de geadresseerde om de e-mailbeheerder te laten weten dat uw e-mailsysteem geen verbinding kan maken met hun e-mailsysteem. Geef de geadresseerde onderstaande foutdetails. Waarschijnlijk is de e-mailbeheerder van de geadresseerde de enige die dit probleem kan oplossen.

Zie dit artikel: https://go.microsoft.com/fwlink/?LinkId=389361 voor meer informatie en tips voor het oplossen van dit probleem.



Diagnostische gegevens voor beheerders:

Bronserver: SV0P279MB0028.NORP279.PROD.OUTLOOK.COM
Ontvangende server: SV0P279MB0028.NORP279.PROD.OUTLOOK.COM

michele@locati.it
6/13/2021 7:10:29 PM - Server at SV0P279MB0028.NORP279.PROD.OUTLOOK.COM returned '550 5.4.317 Message expired, cannot connect to remote server(554 mxdhfe10.ad.aruba.it bizsmtp sVQtlntbBGgbK IP 40.92.55.28 reverse non valido / Your IP 40.92.55.28 has no valid reverse DNS (PTR))'
6/13/2021 7:06:06 PM - Server at locati.it (62.149.128.72) returned '450 4.4.317 Cannot connect to remote server [Message=554 mxdhfe10.ad.aruba.it bizsmtp sVQtlntbBGgbK IP 40.92.55.28 reverse non valido / Your IP 40.92.55.28 has no valid reverse DNS (PTR)] [LastAttemptedServerName=locati.it] [LastAttemptedIP=62.149.128.72:25] [OL1NOR01FT025.eop-nor01.prod.protection.outlook.com](554 mxdhfe10.ad.aruba.it bizsmtp sVQtlntbBGgbK IP 40.92.55.28 reverse non valido / Your IP 40.92.55.28 has no valid reverse DNS (PTR))'

Oorspronkelijke berichtkoppen:

ARC-Seal: i=1; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=none;
 b=SG2YlVK4vo6dojZUo0ts1JT2iAg4d8JenCW950kRu7/PRtw/YjGD0jj0933PiFNBelFZL7KqAYs90GH7k3Sd+PVJJAoM4tQGzxggAviBq6Buh1hgDUyRmMEU9wKQovWh23JxBfRtNjCnR+65N6vA7V7VQ9XSN8gPMIuJImXpzs8Kp9MpHNgjJFp4tOtCSdsgr3mZku9g6H8h3dMxIKIOg0q/ioWJxs+cCbGQxV/PsFth6LOseF2IhG3W1HNQQWk89sznMa738mXHQdrICYYVaDRXGc3gt7nfSxEa7b7jYugT0gZxRjuBojwXAmLSx6nZsv808t9e7Ro29EPrrfitOQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
 s=arcselector9901;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
 bh=irNPolqJKeShXmzoediY4YnGdgFYgI5JGKAJSNEMIXk=;
 b=cDsp4Q84LFFJhBw2AASNtTxuNdS2/XYEpgn7BR8KBD0c6rkq9iBqg0AKGyYk+EjMWREC3JKGmvlYgZCHrmOGSRgq/gP+hVIksxbBYXj39z6Chp9bU/OOmdxJ5PkBAZRqQ5jurcHieJgP7vwn7vwvXcAljV/sncLR5Ac9fZATI760dzfTjl0KktpLKnhZ9yT8fyOF943qRvKd9Y37Z8OMjH6sx5EYoVa35T7vpkhZ9x1aoWEsZYphvUsK2whTmD815nTCdZKJsnwiGHzV5vRISq1FxLX4jTmsrdR/QvKVfDjCPSY9z4TgCU80H1gMA8n85FxqoI6GzdtZ8gNHdOcq7g==
ARC-Authentication-Results: i=1; mx.microsoft.com 1; spf=none; dmarc=none;
 dkim=none; arc=none
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=outlook.com;
 s=selector1;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
 bh=irNPolqJKeShXmzoediY4YnGdgFYgI5JGKAJSNEMIXk=;
 b=aBKy1Ca7Ae5xcQwjpohAlCYpUN8vCmFVFV/5sPaV73MN0MGFjfj7XYIh8ZXgEq4NK/aBPpCwbGs8oKQGgC5RjDmSoIGNeIXk3JlToGeXfQvpUSGqpezb3DwGySAILyT1sqTXJUiRVplP+9d+BuXp9e1XAioFRTt8zf9EMuy3UHaAh7bYRuII7Xz9uXbx02osDz4hnCaq2hq649Kdif1l9DlfZSNQi0IzHW6mpyLVRy4aRtQMfScuHpUnKKq2MwaLqjdXGErwhVbg93QKcc2xSQpR5qch0cKFiJBn2E4hbR/az3VLtBt0eV673iF/yX4eKKs802YXcnbTfAdQeIsPCw==
Received: from SV0P279MB0412.NORP279.PROD.OUTLOOK.COM (2603:10a6:f10:18::14)
 by SV0P279MB0028.NORP279.PROD.OUTLOOK.COM (2603:10a6:f10:9::12) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.4219.21; Sat, 12 Jun
 2021 19:09:57 +0000
Received: from SV0P279MB0412.NORP279.PROD.OUTLOOK.COM
 ([fe80::cd89:1fe5:935e:b148]) by SV0P279MB0412.NORP279.PROD.OUTLOOK.COM
 ([fe80::cd89:1fe5:935e:b148%7]) with mapi id 15.20.4219.025; Sat, 12 Jun 2021
 19:09:57 +0000
From: Thomas De Rocker <thomasderocker@outlook.com>
To: Michele Locati <michele@locati.it>, "mlocati@gmail.com"
   <mlocati@gmail.com>
Subject: Re: Audacity 3.0.3 on Transifex
Thread-Topic: Audacity 3.0.3 on Transifex
Thread-Index: AQHXXg5BolP82TK3r0K/rhb3f8jFSasNcFF4gAG0ZtuAAAJVjoABmagP
Date: Sat, 12 Jun 2021 19:09:57 +0000
Message-ID: <SV0P279MB0412B88EFA029E483E887C3BD3339@SV0P279MB0412.NORP279.PROD.OUTLOOK.COM>
References: <CAGen01jJ7Dv-PuxD_Bh-RO+Omrfc2vuKOd8SOu7zebvPE5tjtw@mail.gmail.com>,<SV0P279MB0412CB3CD83D722A11BD1029D3359@SV0P279MB0412.NORP279.PROD.OUTLOOK.COM>,<SV0P279MB0412D5EBFA32C9B47D278742D3349@SV0P279MB0412.NORP279.PROD.OUTLOOK.COM>,<SV0P279MB04124011D184CDE93A648785D3349@SV0P279MB0412.NORP279.PROD.OUTLOOK.COM>
In-Reply-To: <SV0P279MB04124011D184CDE93A648785D3349@SV0P279MB0412.NORP279.PROD.OUTLOOK.COM>
Accept-Language: nl-BE, en-US
Content-Language: nl-BE
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
x-ms-exchange-messagesentrepresentingtype: 1
x-tmn: [VpasJ112e99mn3oXCMkRTKkyG8dyJfgn]
x-ms-publictraffictype: Email
x-ms-office365-filtering-correlation-id: 2c41b516-8962-4ca5-2122-08d92dd5ab2d
x-ms-traffictypediagnostic: SV0P279MB0028:
x-microsoft-antispam: BCL:0;
x-microsoft-antispam-message-info: X1xvl8OQzbB9wtT7msST41dbTNXP8ldWVCBDQgMHMsOPf/ClmBtWJjdE6HYPc2Nehkl5QwktADuyiv38u1dIH0IfYyDTsTJr2r1Y2T4CVnwVyta94edInzZ4TGrtsqgAqpr9l1j7foauYCi0M20/0vev++zrORReWu3ZkrauvfM1IQWj672ZKakOOMNKYSrzsb5xiLBwH6kLb8/zMJ50I7wz5O9j5rLTz7B2jivICswOd8lCvwy3tgPRX0Drz1V+ZonvWLt0BFwLctaeewXXRmpwc8qPJYdX2gLrlNKP9gmQOEq0sxNr2FxWVcNyuEQ+ZkF/dQXeUUVyfC3IqvGO6JVw/leTfi1HSQrllw0Nqbywn9rbdLohlLfxhGILBNNuqWmGGXZdcB/qhp+AGJ+FjA==
x-ms-exchange-antispam-messagedata: LNn5oAus5ykZDaeWPK/6ELmFJuUjZ5bpL0S02wHRiPmb4GfYAyeuRn6hUiTHQedR3jq1GhLDeJgX7kkvmqud+b2talS+4hk0NEqCg9FW23yFnnopoZEvRThz7/09kzCUCSZ+1Rkygfbt0cz2odFCAw==
x-ms-exchange-transport-forked: True
Content-Type: multipart/alternative;
 boundary="_000_SV0P279MB0412B88EFA029E483E887C3BD3339SV0P279MB0412NORP_"
MIME-Version: 1.0
X-OriginatorOrg: outlook.com
X-MS-Exchange-CrossTenant-AuthAs: Internal
X-MS-Exchange-CrossTenant-AuthSource: SV0P279MB0412.NORP279.PROD.OUTLOOK.COM
X-MS-Exchange-CrossTenant-RMS-PersistedConsumerOrg: 00000000-0000-0000-0000-000000000000
X-MS-Exchange-CrossTenant-Network-Message-Id: 2c41b516-8962-4ca5-2122-08d92dd5ab2d
X-MS-Exchange-CrossTenant-originalarrivaltime: 12 Jun 2021 19:09:57.1566
 (UTC)
X-MS-Exchange-CrossTenant-fromentityheader: Hosted
X-MS-Exchange-CrossTenant-id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-MS-Exchange-CrossTenant-rms-persistedconsumerorg: 00000000-0000-0000-0000-000000000000
X-MS-Exchange-Transport-CrossTenantHeadersStamped: SV0P279MB0028
